"""Wave A self-hosting: assess build-plan phase goals as requirements.

Treats each of the 16 build-plan phase goals as a synthetic
Requirement and runs the INCOSE GtWR quality checker against it.
Outputs a Markdown report to docs/development/plan-self-assessment.md.
"""

from __future__ import annotations

from pathlib import Path
from typing import Final

from vnvspec.core._internal.gtwr_rules import RuleViolation
from vnvspec.core.requirement import Requirement

# ---- Phase goals (extracted from the build plan) ----

_PHASE_GOALS: Final[list[tuple[str, str]]] = [
    (
        "PLAN-PHASE-01",
        "Empty but correctly wired Python 3.11+ package that passes `just check`.",
    ),
    (
        "PLAN-PHASE-02",
        "Define the Pydantic v2 models for the spec language. All domain-agnostic.",
    ),
    (
        "PLAN-PHASE-03",
        "`Requirement.check_quality()` returns a list of `RuleViolation` objects.",
    ),
    (
        "PLAN-PHASE-04",
        "`Spec.trace_graph()` returns a directed acyclic graph"
        " of links between requirements, hazards, evidence,"
        " ODDs.",
    ),
    (
        "PLAN-PHASE-05",
        '`vnvspec.registries.load("iso_pas_8800")` returns'
        " a typed registry object; 5 bundles shipped.",
    ),
    (
        "PLAN-PHASE-06",
        "`IOContract` can be backed by pydantic for records or pandera for dataframes.",
    ),
    (
        "PLAN-PHASE-07",
        "Publish the pluggability contract (ModelAdapter, TestRunner, Exporter protocols).",
    ),
    (
        "PLAN-PHASE-08",
        "`vnvspec.torch.TorchAdapter` wraps any `nn.Module` and implements `ModelAdapter`.",
    ),
    (
        "PLAN-PHASE-09",
        "`vnvspec.torch.TransformerAdapter` wraps HF `transformers` encoder and seq2seq models.",
    ),
    (
        "PLAN-PHASE-10",
        "`AutoregressiveAdapter` and `VLMAdapter`.",
    ),
    (
        "PLAN-PHASE-11",
        "`spec.generate_tests()` emits a pytest file;"
        " `spec.generate_hypothesis()` emits property tests.",
    ),
    (
        "PLAN-PHASE-12",
        "Four export formats (HTML, Markdown, GSN Mermaid, Annex IV techdoc).",
    ),
    (
        "PLAN-PHASE-13",
        "`vnvspec` CLI command.",
    ),
    (
        "PLAN-PHASE-14",
        "MkDocs Material site builds cleanly.",
    ),
    (
        "PLAN-PHASE-15",
        "`examples/` each run standalone; `tests/integration/` pass.",
    ),
    (
        "PLAN-PHASE-16",
        "A releasable wheel.",
    ),
]


def _build_requirements() -> list[Requirement]:
    """Create synthetic Requirement objects from phase goals."""
    reqs: list[Requirement] = []
    for req_id, statement in _PHASE_GOALS:
        reqs.append(
            Requirement(
                id=req_id,
                statement=statement,
                rationale=("Build-plan milestone for vnvspec development."),
                verification_method="inspection",
                acceptance_criteria=["Phase deliverable is complete and passes CI."],
            )
        )
    return reqs


def _format_violations(
    violations: list[RuleViolation],
) -> str:
    """Format a list of violations as a markdown bullet list."""
    if not violations:
        return "  - *No violations*\n"
    lines: list[str] = []
    for v in violations:
        lines.append(f"  - **{v.rule} {v.name}** ({v.severity}): {v.message}")
    return "\n".join(lines) + "\n"


def _generate_report(
    reqs: list[Requirement],
) -> str:
    """Run check_quality on each requirement, return markdown."""
    lines: list[str] = [
        "# Wave A Plan Self-Assessment",
        "",
        "This report was auto-generated by `scripts/wave_a_plan_assessment.py`.",
        "It treats each build-plan phase goal as a synthetic Requirement",
        "and runs the INCOSE GtWR quality checker against it.",
        "",
        "## Results",
        "",
    ]
    total_violations = 0
    phases_with_violations = 0

    for req in reqs:
        violations = req.check_quality()
        total_violations += len(violations)
        if violations:
            phases_with_violations += 1

        lines.append(f"### {req.id}")
        lines.append("")
        lines.append(f"**Statement:** {req.statement}")
        lines.append("")
        lines.append(f"**Violations ({len(violations)}):**")
        lines.append("")
        lines.append(_format_violations(violations))

    lines.append("## Summary")
    lines.append("")
    lines.append(f"- **Total phases:** {len(reqs)}")
    lines.append(f"- **Phases with violations:** {phases_with_violations}")
    lines.append(f"- **Total violations:** {total_violations}")
    lines.append("")
    lines.append("Most violations stem from the fact that build-plan goals are")
    lines.append("informal milestones, not engineering requirements. They lack")
    lines.append("'shall' language, clear subjects, and are often compound.")
    lines.append("This is expected and demonstrates that the GtWR checker")
    lines.append("correctly flags non-requirement prose.")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    """Entry point for the Wave A self-hosting assessment."""
    reqs = _build_requirements()
    report = _generate_report(reqs)

    repo_root = Path(__file__).resolve().parent.parent
    out_path = repo_root / "docs" / "development" / "plan-self-assessment.md"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(report, encoding="utf-8")

    print(f"Report written to {out_path}")
    print()
    print(report)


if __name__ == "__main__":
    main()
